clear_system_fault:
  name: Clear System Fault
  description: Clear a system fault on a ZipAssist hydrotap.
  fields:
    device_id:
      name: Device ID
      description: The hydrotap ID (UUID) of the device.
      required: true
      example: "631a3385-301b-4c9c-97ed-3a1a50061f5c"
      selector:
        text: {}
    fault_id:
      name: Fault ID
      description: The ID of the system fault to clear.
      required: true
      example: "fault-1"
      selector:
        text: {}